
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNmZHNkcyIsImlkIjoiNWUzNWM0NzJhOGEwYWIwZTUwNjAyYzE2IiwiaWF0IjoxNTgwNjg3NTk2fQ.1jFADvkdLyKsMdz6QyPTNq5vwXFR624B8t5mUbpEIaI

{
  "title": "dfhf",
  "author": "gfds",
  "url": "gsdf",
  "likes": 0
}
